package events

const (
	ROOM_CREATE_EVENT         = "ROOM_CREATE"
	ROOM_JOIN_EVENT           = "ROOM_JOIN"
	HUNCH_CREATE_EVENT        = "HUNCH_CREATE"
	PLAYER_STATE_UPDATE_EVENT = "PLAYER_STATE_UPDATE"
	ROOM_STATE_EVENT          = "ROOM_STATE"
	SCOREBOARD_EVENT          = "SCOREBOARD"
)
